name: CICD test pipeline

on:
  push:
    branches: [ "github_action" ]


jobs:
  setup:
    runs-on: ubuntu-latest  # Runner OS for the job
    steps:
      - uses: actions/checkout@v4  # Checkout the repository
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

  compile:
    runs-on: ubuntu-latest
    needs: setup  # This job runs after the `setup` job finishes successfully
    steps:
      - uses: actions/checkout@v4
      - name: Build with Maven
        run: mvn compile

  test:
    runs-on: ubuntu-latest
    needs: compile  # This job runs after the `compile` job finishes successfully
    steps:
      - uses: actions/checkout@v4
      - name: Run Unit Tests
        run: mvn test



